schema_version: 1

context:
  name: diffeqpy
  version: 2.6.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/diffeqpy-${{ version }}.tar.gz
  sha256: 556db527e998f1ed9b461e46690fb22d2077d2955985020890e386f77170c547

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - jill
    - juliacall >=0.9.28
tests:
  - python:
      imports:
        - diffeqpy
      pip_check: false
      python_version: ${{ python_min }}
about:
  summary: Solving Differential Equations in Python
  license: MIT
  license_file: LICENSE.md
  homepage: http://github.com/SciML/diffeqpy

extra:
  recipe-maintainers:
    - jan-janssen
